CREATE TABLE pessoas (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf           VARCHAR(14)  NOT NULL UNIQUE,
    nome          VARCHAR(40)  NOT NULL,
    idade         INTEGER      NOT NULL,
    criado_em     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE usuarios (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf           VARCHAR(14)  NOT NULL UNIQUE,
    senha         VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    pessoa_id     BIGINT UNIQUE REFERENCES pessoas (id) ON DELETE CASCADE,
    ativo         BOOLEAN      NOT NULL,
    criado_em     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    usuario_id BIGINT      NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    expira_em  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    criado_em  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE agencias (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero        INTEGER      NOT NULL UNIQUE,
    endereco      VARCHAR(100) NOT NULL,
    cidade        VARCHAR(25)  NOT NULL,
    criado_em     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE contas (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero                 INTEGER        NOT NULL UNIQUE,
    saldo                  NUMERIC(15, 2) NOT NULL,
    limite_cheque_especial NUMERIC(15, 2) NOT NULL,
    pessoa_id              BIGINT         NOT NULL REFERENCES pessoas (id),
    agencia_id             BIGINT         NOT NULL REFERENCES agencias (id),
    criado_em              TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    atualizado_em          TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE movimentacoes (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id                  BIGINT         NOT NULL REFERENCES contas (id) ON DELETE CASCADE,
    tipo                      VARCHAR(30)    NOT NULL,
    valor                     NUMERIC(15, 2) NOT NULL,
    saldo_apos                NUMERIC(15, 2) NOT NULL,
    numero_conta_contraparte  INTEGER,
    data_hora                 TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_contas_pessoa ON contas (pessoa_id);
CREATE INDEX idx_contas_agencia ON contas (agencia_id);
CREATE INDEX idx_movimentacoes_conta_data ON movimentacoes (conta_id, data_hora);
CREATE INDEX idx_refresh_tokens_usuario ON refresh_tokens (usuario_id);
