-- Usuário criado com senha temporária precisa trocá-la no primeiro acesso
ALTER TABLE usuarios ADD COLUMN trocar_senha BOOLEAN DEFAULT FALSE NOT NULL;

-- Registro das ações administrativas (quem fez o quê e quando)
CREATE TABLE auditoria (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT,
    usuario_cpf VARCHAR(14),
    acao        VARCHAR(40)  NOT NULL,
    entidade    VARCHAR(20)  NOT NULL,
    entidade_id BIGINT,
    descricao   VARCHAR(255) NOT NULL,
    data_hora   TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_auditoria_data ON auditoria (data_hora);
CREATE INDEX idx_usuarios_pessoa ON usuarios (pessoa_id);
